# Generated by Django 5.2.1 on 2025-05-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.CharField(choices=[('appetizers', 'Appetizers'), ('main course', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('materials', models.TextField(blank=True, help_text='Comma-separated list')),
                ('instructions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
            ],
        ),
    ]
